### ISSUE TITLE
WebAssembly.Exception

### ISSUE THREAD

**Issue by Polyana-F** [mikepenz/multiplatform-markdown-renderer#336]
![Image](https://github.com/user-attachments/assets/c32dac84-77cf-452e-b439-03876f252714)

I'm getting this on wasm, jvm target works fine.

I spent so many hours trying to make it work, but I failed.

```kt
@Composable
fun App() {
    MaterialTheme {
        Markdown("Hello, *how are you?*")
    }
}
```

```kt
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.runtime.compose)
            implementation(libs.koin.compose)
            implementation(libs.sofia.data)
            implementation(libs.multiplatform.markdown.renderer.core)
            implementation(libs.multiplatform.markdown.renderer.m2)
            implementation(libs.multiplatform.markdown.renderer.code)
            implementation(libs.multiplatform.markdown.renderer.coil3)
            implementation(libs.coil.compose)
            implementation(libs.coil.network.cache.control)
            implementation(libs.coil.network.ktor)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.multiplatform.settings)
            implementation(libs.coil.svg)
```

```toml
[versions]
agp = "8.9.0"
androidx-lifecycle = "2.8.4"
compose-multiplatform = "1.8.0-alpha04"
junit = "4.13.2"
kotlin = "2.1.10"
koin="4.0.2"
sofia="0.1.0-SNAPSHOT"
kotlinx-coroutines = "1.10.1"
markdown-renderer="0.32.0-b02"
coil="3.1.0"
ktor="3.1.1"
kotlinx-serialization-json="1.8.0"
multiplatform-settings="1.3.0"
androidx-activityCompose = "1.10.1"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
```

I'm replacing all Markdown calls to a simple Text on wasm until I manage to get it working.

```kt
@Composable
private fun MarkdownRenderer(text: String, mdTypography: MarkdownTypography?) {
    if (!platform.isMarkdownSupported) {
        Text(text)
    } else {
        Markdown(
            text,
            modifier = Modifier,
            components = markdownComponents(
                codeBlock = highlightedCodeBlock,
                codeFence = highlightedCodeFence,
            ),
            imageTransformer = MDImageLoader,
            typography = mdTypography ?: mdTypography()!!
        )
    }
}
```
